### ISSUE TITLE
Temporarily banned IPs

### ISSUE THREAD

**Issue by paul5196** [devnulli/EvlWatcher#101]
I must admit I have been looking for something to do this for a Win 2008 R2 server to remove the tedium of adding IPs to a firewall blacklist. But to get to the point There are no entries appearing in the Temporarily Banned IP list? I have checked the application can extract IPs from an XML security record and I have added a bunch of IPs to block. Is there something to adjust to to see temporarily banned IPs.
Before you ask this web server is under constant attack. Our edge firewall has a limited number of profiles that I can add for IP addresses to ban. So I would have expected to see some activity for temporary IP bans. 
![image](https://user-images.githubusercontent.com/11156198/180441814-e503fc87-c6ac-42f2-bcac-888f397d0613.png)
Is this normal behaviour or should there be some entries . My event log file shows the server is being hit by failed logins once every 2 -3 seconds.

**Comment by devnulli** [comment]
do you see any bans or finds in the Live Tab?

**Comment by boikyeet** [comment]
Same problem here.

Here's a log entry from an IP which should have been banned by now:

![image](https://github.com/devnulli/EvlWatcher/assets/46041032/4f293ce4-5240-4e35-82b3-cf77b4a2278b)

**Comment by boikyeet** [comment]
> Here's a log entry from an IP which should have been banned by now:

This was a mistake on my part. I wrongly assumed EvlWatcher would be preconfigured to ban connection attempts from invalid users.

I made a rule for this and it seems to be working fine now.

That being said, I think it would be nice if there was a way to have multiple non mutually exclusive boosters in a single rule.

Currently if I have a rule which goes:

```
<RegexBoosters>
        <Booster>Failed password</Booster>
	<Booster>Invalid user</Booster>
</RegexBoosters>
```

It will only take into account events that contain both boosters, instead of either one or the other.

This would avoid having multiple redundant rules in the config.xml file

**Comment by devnulli** [comment]
then this is solved
