### ISSUE TITLE
Option to send some kind of notification when a banned IP enters the list

### ISSUE THREAD

**Issue by worm91** [devnulli/EvlWatcher#110]
It can be an email or telegram

**Comment by JReming85** [comment]
That would result in a lot of spam.

You might be better of creating a scheduled task that polls the rules and compares for new entries and have it run on a schedule to get a changelog

**Comment by devnulli** [comment]
Evlwatcher is meant to be kept simple. It also produces Log entries when it bans, from where a more sophisticated Tool or a power shell Scripts could pick Up the information .

Telegram part would be easy, but evlwatcher it is running as local system (not local Network), meaning that it itself can not communicate over the Network (and therefore not post to Telegram api or etc.)  i think thats a good thing, because so it can be trusted to Not collect data or whatnot.

ill close this, it really would be a nice feature, agree on that, but it is out of the scope of what evlwatcher should do
