### ISSUE TITLE
Portable version.

### ISSUE THREAD

**Issue by paolosezart** [devnulli/EvlWatcher#119]
Is a portable version expected?

**Comment by devnulli** [comment]
what do you mean with portable version?

**Comment by paolosezart** [comment]
I mean, running the program without installing it into the system. Without leaving traces in the registry and other folders. Saving all settings in the program folder

**Comment by SmilerRyan** [comment]
Currently it seems like this is possible by extracting the files from the setup with 7zip, you just need to manually run the EvlWatcher.exe as administrator. Since the config is already in the same directory, is already does work as if it is portable.
If it's possible with the installer (NSIS), it would be enough to have an option to extract the files (no admin needed), or install the files and service normally.I have attached a screenshot of how it looks extracted and running portably.

![Screenshot 2024-06-10 114737](https://github.com/devnulli/EvlWatcher/assets/14893385/5a1c16b9-161d-441b-809f-8ed0cbaabb24)

**Comment by devnulli** [comment]
thats correct, the executable itself does not have any (relevant) dependencies to outside its folder, so it can be extracted and just run. be advised tho, that for reading log entries and modifying the firewall you would need the admin privileges, and also, if evlwatcher was not installed before, the first call would create an eventsource called EvlWatcher, which will also need admin rights
