### ISSUE TITLE
Implement logging configuration and logging. 

### ISSUE THREAD

**Issue by mgraf444** [devnulli/EvlWatcher#15]
Hello,

Does this log failed login attempts to a log file anywhere? I only see blacklisted ips in the config.xml file.

Thanks

**Comment by devnulli** [comment]
Hi,

In older versions, it did. EvlWatcher used to log into it's own Eventsource names "EvlWatcher" , however, the current version doesn't log login attempts, because into the eventlog, because it uses the Eventlog to find those attempts, and it somehow felt .. crazy .. to log a logentry...  It could, however, log when someone gets banned etc, in older versions. 

I don't know why I removed that, probably because there was no way of turning it of, and it produced a whole lot of logs.

But I will bring it back in in the next version: as part of overhauling the console app, there will be the possibility to make logging settings.

**Comment by devnulli** [comment]
Made this an issue.
